apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: production
  name: jenkins-rolebinding
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: production
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
